// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZqxg-f2aE3bH2ZfmV93hpo0-Y27VqEBQ',
    appId: '1:740869963013:web:86cd4ec8877e5f45d8cb6c',
    messagingSenderId: '740869963013',
    projectId: 'mynotesfirstflutterapp',
    authDomain: 'mynotesfirstflutterapp.firebaseapp.com',
    storageBucket: 'mynotesfirstflutterapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA27SGLtAI2zClUd3IcKI51vOHd1Mc5n_A',
    appId: '1:740869963013:android:13673671bb480470d8cb6c',
    messagingSenderId: '740869963013',
    projectId: 'mynotesfirstflutterapp',
    storageBucket: 'mynotesfirstflutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD99bvNY-AIJ5e1vQjWvS-un2qYhQlIUZI',
    appId: '1:740869963013:ios:a82c405b5b2b539cd8cb6c',
    messagingSenderId: '740869963013',
    projectId: 'mynotesfirstflutterapp',
    storageBucket: 'mynotesfirstflutterapp.appspot.com',
    iosClientId: '740869963013-r17mijlvkhkrn00k7jfvss5nrheciu9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotesflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD99bvNY-AIJ5e1vQjWvS-un2qYhQlIUZI',
    appId: '1:740869963013:ios:4aba1ed7253c4da6d8cb6c',
    messagingSenderId: '740869963013',
    projectId: 'mynotesfirstflutterapp',
    storageBucket: 'mynotesfirstflutterapp.appspot.com',
    iosClientId: '740869963013-mkavu6j8klcd194av88nesg08t2e3l5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotesflutter.RunnerTests',
  );
}
